"""add_status_to_matches

Revision ID: c7628b0d7489
Revises: 2d8d820655d7
Create Date: 2026-06-11 19:32:50.461488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7628b0d7489'
down_revision: Union[str, Sequence[str], None] = '2d8d820655d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('status', sa.String(length=20), server_default='scheduled', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'status')
    # ### end Alembic commands ###
